// <auto-generated />
using System;
using GameRankServer.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameRankServer.Storage.Migrations
{
    [DbContext(typeof(GameRankContext))]
    [Migration("20190619124208_update1")]
    partial class update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GameRankServer.Storage.GameRanks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<long>("GameId");

                    b.Property<long>("Score");

                    b.Property<long>("Userid");

                    b.HasKey("Id");

                    b.ToTable("gameranks");
                });

            modelBuilder.Entity("GameRankServer.Storage.GameUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("IdentityId");

                    b.Property<string>("NickName");

                    b.Property<long>("RegisterGameId");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GameRankServer.Storage.Games", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GameId");

                    b.Property<string>("GameName");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("games");
                });
#pragma warning restore 612, 618
        }
    }
}
